/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BPigDrawingPane.java
 *
 * Created on Mar 10, 2010, 12:50:43 AM
 */

package blasterpig;

import java.awt.*;
import java.awt.image.BufferedImage;
/**
 *
 * @author blackMamba
 */
public class BPigDrawingPane extends javax.swing.JPanel {

    /** Creates new form BPigDrawingPane */
    private BPigController huston;
    private boolean hasController;

    public BPigDrawingPane() {
        initComponents();
        hasController = false;
    }

    public void setController(BPigController huston)
    {
        this.huston = huston;
        hasController = true;
    }

    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D)g;
        BufferedImage drawnStrand;

        
        if(hasController){
            drawnStrand = huston.drawFold();
            if(drawnStrand != null){
                g2.drawImage(drawnStrand, null, 1, 1);
            }
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
